# Generated by Django 6.0.3 on 2026-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media')),
                ('narxi', models.IntegerField()),
                ('skidkasi', models.IntegerField()),
                ('tavsifi', models.CharField(max_length=100)),
            ],
        ),
    ]
