# Generated by Django 6.0.3 on 2026-05-12 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_category_id_alter_item_id_alter_main_branch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base.card'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='rasm',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='skidkasi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main_branch',
            name='picture',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
