# Generated by Django 6.0.3 on 2026-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_card_created_at_alter_carditem_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
